app = "stock-nexus-backend"
primary_region = "ord"

[build]

[env]
  NODE_ENV = "production"
  PORT = "5000"
  JWT_EXPIRES_IN = "7d"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
