services:
  - type: web
    name: stock-nexus-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: ./simple-start.sh
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://stock-nexus-84-main-2-kmth.vercel.app
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_app_password
    database:
      name: stock-nexus-db
      plan: free
      databaseName: stock_nexus
